### ISSUE TITLE
Question: how do I use "query" functionality from terminal?

### ISSUE THREAD

**Issue by mailsanchu** [balta2ar/brotab#103]

**Comment by drocta** [comment]
Have you tried `brotab query --help`? It gives a list of the arguments you can use with it, and generally how to use them.

Does this answer your question? If not, can you be more specific?

**Comment by mailsanchu** [comment]
`awk` is spliting the output by space and getting the tab id. Is it possible only to get the tab id in the output?

**Comment by drocta** [comment]
I don't know of a way to do that with just brotab.
Personally, I use `cut` for that, instead of `awk`.

Actually, I'm pretty sure that the brotab command line program receives the information in that format when it receives it from the browser extension. It isn't doing that itself. So, in order for it to give you the split version, it would have to do the splitting itself.
Which, it could, but I don't think there is an option for that at present.

**Comment by mailsanchu** [comment]
That is perfectly fine. Closing the ticket

**Comment by mailsanchu** [comment]
Last question
Can we get multiple domains using query like facebook or github?
`brotab query -url *://*.facebook.com/*`

**Comment by drocta** [comment]
Yup! `brotab query -url *://*.facebook.com/* -url *://*.github.com/*`
