### ISSUE TITLE
No "bt" or "brotab" command found after "pip install brotab"

### ISSUE THREAD

**Issue by cglmrfreeman** [balta2ar/brotab#28]
The instructions seem a bit unclear here. I am able to run `pip install brotab` just fine, but `bt install` and/or `brotab install` do nothing after this. I am using OpenSUSE with the extension already installed in Firefox. `cnf bt` and `cnf brotab` also return no results.

**Comment by balta2ar** [comment]
> do nothing after this

If "bt" command cannot be found, it means that `bt` is not in your PATH. That is the configuration aspect of your system, brotab can't and shouldn't do anything about this, you should configure your PATH accordingly.

When you do `pip install`, it usually prints file paths where files are being copied to. Executables are usually created in `$HOME/.local/bin/`, so that's the path you may want to add to your PATH. But again, it may vary depending on your system.

You can try the following:

1. `pip install --user brotab` -- this will explicitly tell pip to install `brotab` into the current user folder. Notice which paths are printed on the screen when you run it, `bt` should be mentioned there, so you can figure our the corrert directory you need to add to your PATH.
2. `sudo pip install brotab` -- this will install brotab binary globally.

**Comment by cglmrfreeman** [comment]
Ah, of course I should have tried sudo! I don't mind it being global and it works just fine, oopsies! Thank you!
