### ISSUE TITLE
Explanation of permissions?

### ISSUE THREAD

**Issue by dufferzafar** [balta2ar/brotab#30]
I understand the permission to access tabs & run native client but, why does it require the permission to "access data for all websites"?

**Comment by balta2ar** [comment]
To implement `bt words` and `bt text` commands.

**Comment by balta2ar** [comment]
It would actually be nice to have granular permissions, e.g. if you don't use `bt words` or `bt text` commands, you don't have to give the extension too much access, similarly to how it's done in apple/android ecosystem. Here with extensions it's all or nothing, AFAIK.

**Comment by xeor** [comment]
What about building another version as well? One named "brotab-noout" or something, that can be the same but without support for `bt [word|text]`.

At least for me, I'm super skeptical using anything that needs `access data for all websites`

**Comment by balta2ar** [comment]
My current life situation is such that I don't really devote much of my leisure time to open source contributions. But when I do, even with the current state of things it's quite a hassle to release both chromium and firefox versions, I always have to reread my release procedure notes and be super focused to not mess things up. Having another branch without `word/text` will only make it worse, so I have zero intention doing that :man_shrugging:

I understand your concern though, and as ugly as it may sound, if this extension makes a difference in your life, I think you may be better off stripping html and text parts of the extension manually and installing it locally in dev mode. I don't think you'll miss out on anything or will have to do it often since as you can see this extension doesn't really change much.

**Comment by xeor** [comment]
Thanks for the honest reply @balta2ar , I thought maybe you had everything automated using GitHub actions or something :p 
I go you can consider a pr if someone do automate and fix this.
I've never created an extension myself, but I might do the pr some time

**Comment by yannrouillard** [comment]
Hi @balta2ar 

It seems it is now possible to configure [optional permissions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions) for an extension.

Would you be opened to a PR implementing optional permission for "access data for all websites"?
