### ISSUE TITLE
Get HTML instead of text?

### ISSUE THREAD

**Issue by dufferzafar** [balta2ar/brotab#31]
`bt text $(bt active)` is useful, but sometimes I'd actually prefer to just get the HTML and do the parsing myself. 

Could you provide a command to get the HTML from the DOM?

**Comment by balta2ar** [comment]
Implemented in version 1.3.0. Note that both pip and browser extension update are required. Firefox version has been published already, but Chrome version is going to be available later after the review (from days to weeks).

**Comment by balta2ar** [comment]
Oh and for consistency with "bt text", newlines and tabs are removed by default before sending HTML back from the browser (so that HTML fits on a single line). I hope it's OK for your purposes. You can play with `--delimiter-regex` argument though, but I spent half an hour trying to make it return HTML as is and dropped that idea.

**Comment by dufferzafar** [comment]
Why is this required though? I mean why does it all have to fit a single line?

**Comment by balta2ar** [comment]
That way you get a nice columnar output similar to bt text

**Comment by dufferzafar** [comment]
I'm getting this with with brotab 1.3.0 - both pip package and firefox extension are at 1.3.0

`Cannot access API b.    localhost:4626  874178  firefox: HTTP Error 404: NOT FOUND`

**Comment by balta2ar** [comment]
Could you make sure you reloaded the plug-in or restarted the browser? It must be the old version of the mediator app running
